path:
  data: ./data/raw
dates:
  fall: 09-01
  spring: 02-01
keywords:
  ors: ['ors']
  prc: ['prc', 'project code', 'phase']
log_level: DEBUG
test:
  excel_filename: 'test_excel_name.xlsx'
  excel_wrapper_names: ['file1.xlsx', 'file2.xlsx', 'file3.xlsx']
  excel_wrapper_data: ['content1', 'content2', 'content3']